export const shipments: any[] = [
  {
    id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    trackingNumber: "BG-20260311-XYZ12",
    customerId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    assignedToId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    status: "PENDING",
    senderName: "Emeka Obi",
    senderPhone: "08011111111",
    senderAddress: "10 Awolowo Road, Victoria Island",
    senderCity: "Lagos Cit",
    senderState: "Lagos",
    recipientName: "Chidi Nwosu",
    recipientPhone: "08022222222",
    recipientAddress: "5 Ekwulobia Road",
    recipientCity: "Aba",
    recipientState: "Abia",
    description: "string",
    weight: 150, 
    weightUnit: "KG",
    cartons: 5,
    serviceType: "STANDARD",
    zone: 2,
    distanceKm: 464,
    quotedPrice: 27000,
    finalPrice: 27000,
    currency: "NGN",
    surchargeBreakdown: [
      {
        type: "FUEL",
        label: "Fuel Surcharge",
        description: "Adjusted weekly based on market prices",
        amount: 1485,
      },
    ],
    paymentStatus: "PENDING",
    cutoffWarning: false,
    isFragile: true,
    requiresInsurance: true,
    insuranceValue: 0,
    pickupDate: "2026-05-06T16:33:15.511Z",
    estimatedDelivery: "2026-05-06T16:33:15.511Z",
    deliveredAt: "2026-05-06T16:33:15.511Z",
    notes: "string",
    createdAt: "2026-05-06T16:33:15.511Z",
    updatedAt: "2026-05-06T16:33:15.511Z",
  },
];



 export const ticketsSampleData = [
  {
    id: "TCK-001",
    subject: "Package not received after 7 days",
    category: "TRACKING",
    trackingNumber: "SHP385f64",
    priority: "NORMAL",
    status: "OPEN",
    email: "eol@gmail.com",
    username: "Shola Judge",
  },
  {
    id: "TCK-002",
    subject: "Payment was deducted twice",
    category: "PAYMENT",
    trackingNumber: "SHP9283jd",
    priority: "HIGH",
    status: "IN_PROGRESS",
    email: "user2@gmail.com",
    username: "Tunde Ade",
  },
  {
    id: "TCK-003",
    subject: "Dispute on delivery pricing",
    category: "PRICING_DISPUTE",
    trackingNumber: "SHP1122aa",
    priority: "URGENT",
    status: "ESCALATED",
    email: "client3@gmail.com",
    username: "Aisha Bello",
  },
  {
    id: "TCK-004",
    subject: "Package arrived damaged",
    category: "DAMAGED_GOODS",
    trackingNumber: "SHP7788xy",
    priority: "HIGH",
    status: "RESOLVED",
    email: "user4@gmail.com",
    username: "Emeka Okafor",
  },
  {
    id: "TCK-005",
    subject: "Late delivery beyond expected time",
    category: "DELIVERY_ISSUE",
    trackingNumber: "SHP9900lk",
    priority: "NORMAL",
    status: "IN_PROGRESS",
    email: "user5@gmail.com",
    username: "Zainab Musa",
  },
  {
    id: "TCK-006",
    subject: "Unable to login to account",
    category: "ACCOUNT",
    trackingNumber: "SHP6677bb",
    priority: "LOW",
    status: "CLOSED",
    email: "user6@gmail.com",
    username: "John Doe",
  },
  {
    id: "TCK-007",
    subject: "General inquiry about shipment",
    category: "OTHER",
    trackingNumber: "SHP4433zz",
    priority: "LOW",
    status: "OPEN",
    email: "user7@gmail.com",
    username: "Mary Johnson",
  },
];
